### ISSUE TITLE
Raw text shown for password IOTSTOCK

### ISSUE THREAD

**Issue by Shaggs** [hiramvillarreal/iotpos#14]
When a user or admin edits any  password it's shown in raw text not *

Possible to change to * when entering?

**Comment by hiramvillarreal** [comment]
Hello Shaggs nice to meet you, yes letme find the fiels propierties to change that,Did you install the QT creator IDE?

**Comment by Shaggs** [comment]
I have just downloaded your program. 

What can I use to edit a few things only coding I know is python and c++ is on my list to learn so this may be my ticket to learn

**Comment by hiramvillarreal** [comment]
Sure you can Help,:
Plase see the last lines >184 from the INSTALL file you would find the how to install QTcreator IDE, you can do it on the Pi or other PC running UBUNTU for example.

**Comment by Shaggs** [comment]
@hiramvillarreal

Found how to make it a password will change later tonight and will push update

**Comment by hiramvillarreal** [comment]
Great, I am testing it now, by the way, had you evre try to create a piping to bash command? something like: curl -sSL https://install.pi-hole.net | bash

**Comment by Shaggs** [comment]
Piping bash commands saves no time this way it's a simple sh script
