### ISSUE TITLE
Install script stop at line 9

### ISSUE THREAD

**Issue by hiramvillarreal** [hiramvillarreal/iotpos#19]
Hello it seem before line 9 the terminal user is root so at ~cd go to /root:

./install.sh: line 9: cd: iotpos: No such file or directory
begin build
CMake Error: The source directory "/root" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
installing IOTPOS
make: *** No rule to make target 'install'.  Stop.
install complete now to setup database
./install.sh: line 18: cd: /root/iotpos/database_resources: No such file or directory
cat: iotpos_mysql.sql: No such file or directory
Enter password:
all done :)

**Comment by Shaggs** [comment]
Yeah I've just seen that when installing again stand-by for fix

**Comment by Shaggs** [comment]
Fix found remove following lines from install.sh

`cd ~`
`cd iotpos`

As we are already in that folder no need to get out and back in again

**Comment by hiramvillarreal** [comment]
Thanks buddy
