### ISSUE TITLE
Changing "$" into any other currency symbol? 

### ISSUE THREAD

**Issue by Marcbambam** [hiramvillarreal/iotpos#20]
Hi, is it possible to change that currency sign "$"  in any other currency symbol or letters?

**Comment by hiramvillarreal** [comment]
Hello, just change the Locale settings

http://rohankapoor.com/2012/04/americanizing-the-raspberry-pi/

**Comment by Marcbambam** [comment]
Thank you Hiram.

 I changed the region settings and it works well for Philippinnes :-).

I will proceed to learn more or modifying your tickets. My printer is not
high quality so i need a bolder fontsize to make it visible.

However, know that your POS is still used worldwide. I guess that is the
best satisfaction for your work. :-)

Gracias y buenas tardes

Hiram Villarreal <notifications@github.com> schrieb am Mo., 26. März 2018,
15:13:
