### ISSUE TITLE
fractional quantities can't be sold

### ISSUE THREAD

**Issue by bit5mith** [hiramvillarreal/iotpos#21]
Saludos Hiram,
Es posible introducir cantidades decimales para las ventas?
Por ejemplo 0.5 kg.
Cuando se hace una venta y pongo .5 lo redondea a 1.

**Comment by hiramvillarreal** [comment]
Claro se puede con productos que no sean unidad PC, crea la unidad Kg, Mg, Lb, etc. o cualquier otra que no sea Pc solo basta con que des doble clic en la linea cargada y aparece la ventana de fracciones o ejemplo introduzcas 0.5*CODIGOPORDUCTO  y Enter y ya se debe cargar la fracción.

¿Encontraste el manual? si note que no puse ese punto de que tiene que ser otra  unidad que no sea Pc.
iotpos/doc/es/Iotpos_Tareas-Accesos.pdf

En la campo que indica la Qty o cantidad de un producto si le das clic exactamente allí se puede incrementar con flechas pero ese solo mueve unidades  no decimales, dale clic a  los lados  ya sea directamente en el nombre de producto en la lista de cargados para que aparezca la ventana de introduzca fracción. (es una ventana azul)

También opera con PLU-CODE codigos de barras impresos por basculas  que incluyen decimal del producto.

**Comment by bit5mith** [comment]
Ciertamente, el error fue que cuando generé la unidad la puse como "kg" en lugar de "Kg".
Gracias.
