### ISSUE TITLE
How to cancel printing of receipt after partial payment in credit info

### ISSUE THREAD

**Issue by kingcthulhudev** [hiramvillarreal/iotpos#22]
First of all, I'd like to thank you for sharing your work. I have been testing it for a while now and I realized I don't need to print a credit balance sheet after every partial payment in credit info.

How do you disable this?

**Comment by hiramvillarreal** [comment]
Hello Friend, what print method are you using  Cups or Serial?

**Comment by kingcthulhudev** [comment]
Sorry forgot to mention it. I am using Cups.

**Comment by hiramvillarreal** [comment]
Ok, yes we are looking to fix that I will let you know as soon we can.

**Comment by Shaggs** [comment]
working on a fix now. will do some testing and give some options shortly

**Comment by Shaggs** [comment]
So the easiest way would be making a dialog box. This way you can choose if you wish to print it or not. Some people may want to continue to print as displays the current outstanding balance.

Making this a setting in options could be done but is not an easy task.

thoughts?

**Comment by Shaggs** [comment]
used a message box to fix this issue https://github.com/hiramvillarreal/iotpos/pull/25

@hiramvillarreal Upto you to approve
