### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AnosAhmad** [hiramvillarreal/iotpos#28]
[warnings.xlsx](https://github.com/hiramvillarreal/iotpos/files/2873661/warnings.xlsx)

Hello Developer, 

My name is Enas and I am a Ph.D. student. My research focuses on static code analysis. I was looking for open-source software to collect some static code analysis tool warnings. I checked your source code, and I ran one of static code analysis tools over the source code. A number of warnings were generated; some of them may represent true defects in the source code and some may represent false reports, where the tool shows a defect but in reality there is none. 

I need your help by going through the warnings and checking if any of them represent a true defect in your source code. To do that, kindly find the attached file, which contains the warnings. 

Your response and help are highly appreciated. 

Thanks, 
Enas

**Comment by hiramvillarreal** [comment]
Thanks  Enas yes we are aware about this warning they are most warning of QT alignments or unused functions, we are triming the code since some functions are now obsolete on the Mexican market, we will clean them as soon we can.
Regards
