### ISSUE TITLE
Add user not working

### ISSUE THREAD

**Issue by johnbxl1140** [hiramvillarreal/iotpos#3]
Hi,

Firstly I would like to congratulate you on this awsome software.
I have just started playing with it in local and network mode and am very impressed.

I am facing two issues though and don't know what can be done to resolve them.

1. changing the currency to euro seems impossible, it is stuck to $ sign.
2. I tried adding new users, whether it be vendor, supervisor or admin, none are created.

Any help would be greatly appreciated.

Kind regards.

John

**Comment by hiramvillarreal** [comment]
Hi John,
1- You have to change your “Locale” setting  with command sudo raspi_config or in the desktop go to:
	Menu Programs> raspberry pi Configurations>> locale Tab> local configuration yo you local country setting to euros.

2- You probably miss to execute a new Fix script for you database please follow:

cd ~/iotpos/database_resources
cat fix_0.98.sql | mysql -u root –p

That will fix your problem.

Please let me know if it works
Regards.

**Comment by willymarlian** [comment]
I see in the latest image provided in the dropbox, the fix is already patched. Nice!

**Comment by Shaggs** [comment]
You can close this issue also
