### ISSUE TITLE
Duda bbdd

### ISSUE THREAD

**Issue by LUISRK** [hiramvillarreal/iotpos#36]
Buenos días;

Estaba estudiando la aplicación Iotpos y tenia la duda de si puedo hacer una copia de seguridad de las ventas realizadas. La duda me surge porque a pesar de consultar las tablas de mysql no he podido localizar los datos de las ventas y desconozco donde se guardan. Disculpad mi ignorancia. Muchas gracias y un saludo

**Comment by hiramvillarreal** [comment]
Saludos para ver en linea de comandos las tablas  de la base de datos iotposdb:
sudo mysql iotposdb
show tables;
Ejemplo para ver la tabla transactions:
SELECT * FROM transactions;

Si gustas explorar la estructura de la base de datos en una GUI te recomiendo MySQL Workbench

Saludos

**Comment by LUISRK** [comment]
Muchas gracias por resolver mi duda.
