### ISSUE TITLE
iotpos over ubuntu 20.04

### ISSUE THREAD

**Issue by gpardave** [hiramvillarreal/iotpos#37]
it is possible to intall iotpos over ubuntu 20.04?

Es posible instalar la aplicación iotpos en ubuntu 20.04?

Gracias.

**Comment by hiramvillarreal** [comment]
Hi, ubuntu 20.04 is removing some dependences needed to compile, we are looking to solve this issue>
Hola ubuntu 20.04 esta removiendo ciertas dependencias para compilar, estamos buscando una solucion.
Try Ubuntu 18
