### ISSUE TITLE
Reports en iotpos

### ISSUE THREAD

**Issue by newtonsoliveira** [hiramvillarreal/iotpos#43]
Buenas.
Gracias por este proyecto, has salvado mi pelejo.
Hay alguna manera "for Dummies"  de imprimir un relatorio de fin de mes del mes anterior usando en Raspberry?

**Comment by hiramvillarreal** [comment]
Hola mil disculpas no ví tu mensaje pues en iotstock se pueden sacar reportes en forma de csvs.

**Comment by newtonsoliveira** [comment]
Buenas, no he visto antes.
No pudo hacerlo. Puedes decirme cómo?
