### ISSUE TITLE
Barcode Scanner

### ISSUE THREAD

**Issue by willymarlian** [hiramvillarreal/iotpos#5]
Hi,

I really excited trying this POS system, thanks for sharing.

Right now I have installed, try this and that on my Raspberry Pi B+, but still considering to buy hardware. 

I have a couple questions:
1. Will it compatible with Barcode scanner?
2. Will this program be updated? And is there any simple ways to update the program?
3. If I buy a thermal printer, can it just plug on normal USB, instead modified to using GPIO?
4. Will it compatible with Raspberry 3?

Thanks.

**Comment by hiramvillarreal** [comment]
Hello friend. Yes it is compatible with most barcode scanner.
You can update via comand line with git pull origin master and make install again.
Yes you can use any usb CUPS printer as long you can find and compile the driver.
The rpi3 is compatible with a bluethooth disable comand on boot. See INSTALL for instructio  about it.





Enviado desde mi Samsung Mobile de Telcel


-------- Mensaje original --------
De: willymarlian <notifications@github.com>
Fecha: 29/12/2016 1:22 AM (GMT-07:00)
A: hiramvillarreal/iotpos <iotpos@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [hiramvillarreal/iotpos] Barcode Scanner (#5)


Hi,

I really excited trying this POS system, thanks for sharing.

Right now I have installed, try this and that on my Raspberry Pi B+, but still considering to buy hardware.

I have a couple questions:

  1.  Will it compatible with Barcode scanner?
  2.  Will this program be updated? And is there any simple ways to update the program?
  3.  If I buy a thermal printer, can it just plug on normal USB, instead modified to using GPIO?
  4.  Will it compatible with Raspberry 3?

Thanks.

-

**Comment by willymarlian** [comment]
Hi, Thanks for quick response.
I really satisfied with all the answers.

I see for daily reporting, I cannot see the preview. It only has a print button. I hope there will be an update for this feature.
For the moment it is ok because I can pull the data from MySQL.

Can't wait to hear the next update, hoping this program will be better and better.
