### ISSUE TITLE
Program freeze

### ISSUE THREAD

**Issue by ocaman** [hiramvillarreal/iotpos#9]
Hi, when i click quickly a product after 5 o six times, the program freeze and dont response anymore, i cant finalize the program too on ther task manager.

thanks.

**Comment by hiramvillarreal** [comment]
Hello, thanks for the input, do you mean the picture preview?

**Comment by ocaman** [comment]
hi, sometimes on the picture preview, sometimes when adding products, sometimes suddenly.
 I think that would be some problem when accesing to database. I'll try your SD image and i'll be back to comment. Saludos.

**Comment by hiramvillarreal** [comment]
Plase do, I try clicking fast and not had any freeze on my setup.

**Comment by Shaggs** [comment]
@ocaman are you still having this issue? Is it the whole PI that freezes or just the program?

if its just the program may i suggest a new cone followed by new build now some more changes have been made it may help

**Comment by ocaman** [comment]
@Shaggs I just download the SD  image V2 and no problem.

The sd image had items added, now, how can i reset all the data and start again from zero? i mean, no products, tickets, etc. thanks.

**Comment by Shaggs** [comment]
@ocaman I've never used the as image I build from source. @hiramvillarreal I'm sure could help..  A possibly would be using PHP myadmin to remove unwanted data but use with caution

**Comment by hiramvillarreal** [comment]
Hello, you can drop the entire database, just enter to mysql command:

mysql> drop database iotposdb;

 then in command prompt recreate an  blank database with:

cd ~/iotpos/database_resources
cat iotpos_mysql.sql | mysql -u root -p

or restore the database with these commands it only contain 5 products:

cd ~/iotpos/database_resources
sudo mysql -u root -p iotposdb < iotposdb.sql

**Comment by Shaggs** [comment]
with no further comments this shall be closed if needed please re-open
